INSERT IGNORE INTO roles(name) VALUES('ROLE_USER');
INSERT IGNORE INTO roles(name) VALUES('ROLE_USER_VIP');
INSERT IGNORE INTO roles(name) VALUES('ROLE_MODERATOR');
INSERT IGNORE INTO roles(name) VALUES('ROLE_ADMIN');
